export const PRODUCT_SERVICE = 'PRODUCT_SERVICE';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_BRAND_RPC = 'PRODUCT_BRAND_RPC';
export const PRODUCT_CATEGORY_RPC = 'PRODUCT_CATEGORY_RPC';
