export const CART_SERVICE = 'CART_SERVICE';
export const CART_REPOSITORY = 'CART_REPOSITORY';
export const CART_ITEM_REPOSITORY = 'CART_ITEM_REPOSITORY';
export const CART_PRODUCT_RPC = 'CART_PRODUCT_RPC';
export const CART_PRODUCER = 'CART_PRODUCER';
export const CART_CONSUMER = 'CART_CONSUMER';
