version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v3.1.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:3.3.2
    container_name: loki
    volumes:
      - ./loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitor_network

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/:/etc/letsencrypt/live/:ro
      - /etc/letsencrypt/archive/:/etc/letsencrypt/archive/:ro
      - /etc/letsencrypt/renewal/:/etc/letsencrypt/renewal/:ro
    depends_on:
      - grafana
    networks:
      - monitor_network

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6378:6379"
    environment:
      - REDIS_PASSWORD=
    command: ["redis-server", "--requirepass", ""]
    networks:
      - redis_network

networks:
  monitor_network:
  redis_network:
    driver: bridge
