export const ORDER_SERVICE = 'ORDER_SERVICE';
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY';
export const ORDER_ITEM_REPOSITORY = 'ORDER_ITEM_REPOSITORY';
export const ORDER_CART_RPC = 'ORDER_CART_RPC';
export const ORDER_PRODUCT_RPC = 'ORDER_PRODUCT_RPC';
export const ORDER_PRODUCER = 'ORDER_PRODUCER';
export const ORDER_CONSUMER = 'ORDER_CONSUMER';
